config/routes.rb
KameApp::Application.routes.draw do
  get 'tags/:tag', to: 'pictures#index', as: :tag
  
  resources :pictures do
    get :download
  end
  resources :products
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions,      only: [:new, :create, :destroy]
  resources :microposts,    only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  
  root  'static_pages#home'

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/news',    to: 'static_pages#news',    via: 'get'
  

end

app/models/picture.rb
# encoding: utf-8

class Picture < ActiveRecord::Base
  acts_as_taggable # acts_as_taggable_on :tags のエイリアス
  validates :comment, presence: true
  validates_format_of :content_type, 
                      with: /\Aimage/,
                      message: "must be a picture"

  def uploaded_picture=(picture_field)
    self.name         = base_part_of(picture_field.original_filename)
    self.content_type = picture_field.content_type.chomp
    self.data         = picture_field.read
  end

  def base_part_of(file_name)
#    File.basename(file_name).gsub(/[\A\w._-]/, '')
    File.basename(file_name)
  end
end

app/controllers/pictures_controller.rb
# encoding: utf-8

class PicturesController < ApplicationController
  before_action :signed_in_user, only: [:new, :edit, :update, :destroy]
  before_action :admin_user,     only: [:new, :edit, :update, :destroy]
  
  def index
    if params[:tag]
      @pictures = Picture.tagged_with(params[:tag]).paginate(page: params[:page], per_page: 10)
    else
      @pictures = Picture.paginate(page: params[:page], per_page: 10)
    end
  end
  
  def new
    @picture = Picture.new
  end

  def create
    @picture = Picture.new(picture_params)
    if @picture.save
      flash[:success] = "Upload picture sucess!"
      redirect_to @picture
    else
      render 'new'
    end
  end

  def download
    @picture = Picture.find(params[:picture_id])
    send_data(@picture.data,
              filename: @picture.name,
              type: @picture.content_type,
              disposition: "inline")
  end

  def show
    @picture = Picture.find(params[:id])
  end

  def edit
    @picture = Picture.find(params[:id])
  end

  def update
    @picture = Picture.find(params[:id])
    if @picture.update_attributes(picture_params)
       flash[:success] = "Picture updated"
       redirect_to @picture
    else
      render 'edit'
    end
  end

  def destroy
    Picture.find(params[:id]).destroy
    flash[:success] = "Picture destroyed."
    redirect_to pictures_url
  end
          
  private
    # Never trust parameters from the scary internet, only allow the white
    # list through.
    def picture_params
      params.require(:picture).permit(:comment, :uploaded_picture, :tag_list)
    end
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/pictures/_picture.html.erb
<div class="pictures">
  <img src="<%= picture_download_path(picture) %>"/>
  <h3>
    <%= link_to picture.name, picture %>
    <% if signed_in? && current_user.admin? %>
      <%= link_to "delete", picture, method: :delete,
                                 data: { confirm: "You sure?" } %>
    <% end %>
  </h3>
  <p>Tags:  <%= raw picture.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %></p>
  <div class="comment">
    <%= sanitize(picture.comment) %>
  </div>
</div>

app/views/pictures/edit.html.erb
<% provide(:title, "Edit picture") %>
<h1>Update picture</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@picture) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :tag_list, "Tags (separated by commas)" %><br />
      <%= f.text_field :tag_list %>
  
      <%= f.label :comment %>
      <%= f.text_area :comment, rows: 6 %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/pictures/index.html.erb
<% provide(:title, 'All pictures') %>
<h1>All pictures</h1>
<div id="tag_cloud">
  <% tag_cloud Picture.tag_counts_on(:tags).order('count DESC'), %w{css1 css2 css3 css4} do |tag, css_class| %>
    <%= link_to tag.name, tag_path(tag.name), class: css_class %>
  <% end %>
</div>
<%= will_paginate %>
  <div class="row">
    <%= render @pictures %>
  </div>
<%= will_paginate %>

app/views/pictures/new.html.erb
<% provide(:title, 'Upload picture') %>
<h1>Upload picture</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@picture, 
                url: {action: 'create'}, 
                html: {multipart: true}) do |f| %>

      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :tag_list, "Tags (separated by commas)" %><br />
      <%= f.text_field :tag_list %>
  
      <%= f.label :comment %>      
      <%= f.text_area :comment, rows: 6 %>

      <%= f.label :uploaded_picture %>
      <%= f.file_field :uploaded_picture %>

      <%= f.submit "Upload file", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/pictures/show.html.erb
<% provide(:title, @picture.name) %>
<div class="row" >
 <div class="span10 offset1">
  <h3><%= @picture.name %></h3>
  <img src="<%= picture_download_path(@picture) %>"/>
  <p>Tags:  <%= raw @picture.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %></p>
  <%= markdown(@picture.comment) %>
  <p>
    <% if signed_in? && current_user.admin? %>
      <%= link_to "Edit", edit_picture_path(@picture) %>
  <% end %>
  </p>
 </div>
</div>